In [1]:
# 케라스로 변경

In [3]:
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
import numpy
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder

seed = 0
numpy.random.seed(seed)
tf.set_random_seed(seed)


# 1. 붓꽃 데이터 불러오기
dataset = pd.read_csv('./csv/iris.csv', encoding='utf-8',
                      names=['a', 'b', 'c', 'd', 'y'])

# 2. 인풋과 레이블로 나누기
x = dataset.loc[ : , ['a', 'b', 'c', 'd']]
y = dataset.loc[ : , 'y']
x = numpy.array(x)  # (768, 4)
y = numpy.array(y)  # (768, )

# 3. 문자열 인코딩 하기(Label Encoding, One-hot Encoding)
label = LabelEncoder()
y = label.fit_transform(y)  # fit과 transform을 한 줄로 요약하는 방법
#y=label.transform(y)
print(y)

from keras.utils import to_categorical
y = to_categorical(y)
print(y)

# 4. 데이터 나누기
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y,
                                                    test_size=0.3, 
                                                    random_state=0, 
                                                    shuffle = True)

# 5. 모델 설정(DNN)
model = Sequential()
model.add(Dense(32, input_dim=4, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(3, activation='softmax'))

model.summary()

# 6. 모델 컴파일링
model.compile(loss='categorical_crossentropy', # 이진분류는 binary, 다중분류는 categorical
              optimizer='adam',
              metrics=['accuracy'])

# 7. 모델 실행
model.fit(x_train, y_train, epochs=200, batch_size=10)

# 8. 결과 출력
print("\n Accuracy : %.4f" % (model.evaluate(x_test,y_test)[1]))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.

105/105 [==============================] - 0s 104us/step - loss: 0.1566 - accuracy: 0.9714
Epoch 53/200
105/105 [==============================] - 0s 114us/step - loss: 0.1541 - accuracy: 0.9619
Epoch 54/200
105/105 [==============================] - 0s 115us/step - loss: 0.1490 - accuracy: 0.9905
Epoch 55/200
105/105 [==============================] - 0s 105us/step - loss: 0.1424 - accuracy: 0.9714
Epoch 56/200
105/105 [==============================] - 0s 114us/step - loss: 0.1353 - accuracy: 0.9810
Epoch 57/200
105/105 [==============================] - 0s 106us/step - loss: 0.1347 - accuracy: 0.9810
Epoch 58/200
105/105 [==============================] - 0s 104us/step - loss: 0.1333 - accuracy: 0.9714
Epoch 59/200
105/105 [==============================] - 0s 105us/step - loss: 0.1285 - accuracy: 0.9810
Epoch 60/200
105/105 [==============================] - 0s 116us/step - loss: 0.1271 - accuracy: 0.9810
Epoch 61/200
105/105 [==============================] - 0s 115us/step - loss:

105/105 [==============================] - 0s 114us/step - loss: 0.0562 - accuracy: 0.9810
Epoch 131/200
105/105 [==============================] - 0s 104us/step - loss: 0.0562 - accuracy: 0.9810
Epoch 132/200
105/105 [==============================] - 0s 104us/step - loss: 0.0570 - accuracy: 0.9810
Epoch 133/200
105/105 [==============================] - 0s 117us/step - loss: 0.0561 - accuracy: 0.9810
Epoch 134/200
105/105 [==============================] - 0s 104us/step - loss: 0.0588 - accuracy: 0.9810
Epoch 135/200
105/105 [==============================] - 0s 114us/step - loss: 0.0557 - accuracy: 0.9810
Epoch 136/200
105/105 [==============================] - 0s 113us/step - loss: 0.0540 - accuracy: 0.9810
Epoch 137/200
105/105 [==============================] - 0s 104us/step - loss: 0.0578 - accuracy: 0.9905
Epoch 138/200
105/105 [==============================] - 0s 114us/step - loss: 0.0552 - accuracy: 0.9810
Epoch 139/200
105/105 [==============================] - 0s 104us/ste

In [6]:
# 결과 출력
print("\n Accuracy : %.4f" % (model.evaluate(x_test,y_test)[1]))

45/45 [==============================] - 0s 43us/step

 Accuracy : 0.9778
